### ISSUE TITLE
i dont have a mod folder in the h3vr folder do i make one?

### ISSUE THREAD

**Issue by servermeta** [Maiq-The-Dude/BetterHands#1]
as the title said dont have a mod folder and do not know how to make one except (rightclick new folder)

**Comment by DontGetMelond** [comment]
Try starting up h3vr first then close it to see if one comes up, if not
then make one

**Comment by servermeta** [comment]
i did thats why i know the mod doesnt work btw i did make a file ''Mods'' still no work

**Comment by malicean** [comment]
Greetings!

The `mods` folder is created by Deli the first time you start the game after installing it. If this folder does not automatically generate itself, it likely means you failed to install Deli (this includes its dependencies too). With all components installed properly, your H3VR directory should look like this:
![Files and folders contained in the H3VR directory](https://user-images.githubusercontent.com/5615358/106211013-87b4fb00-618d-11eb-9ce7-51684cefcd12.png)

Some common issues include downloading the source code instead of releases (see image below) for BetterHands or its dependencies, misplacing files, or downloading the wrong version of BepInEx (H3VR needs x64).
![Source code dropdown compared to releases banner](https://user-images.githubusercontent.com/5615358/106211532-9819a580-618e-11eb-8101-d37c09cb58d6.png)


Without further information, I cannot help you any further than suggesting you might have one of these problems. If you want more help troubleshooting, I would recommend to go to [Deli's Discord server](https://discord.gg/g8xeFyt42j). The server contains BetterHands as well.

**Comment by servermeta** [comment]
thanks im gonna test is in the morning its currently 1 am

**Comment by servermeta** [comment]
ok so i did it still doesnt work tried to put it in the folder that deli made nothing then into the config nothing i dont know what to do now

**Comment by Endopl** [comment]
I just finished installing the mod so let me help you.
For proper installation of BeplnEx and Deli, after copy-pasting the contents inside the zip file into the H3VR folder, you have to run the game.

For more direct answer, follow these steps.
1) Download the latest BeplnEx, unzip it and copy-paste everything in to the H3VR folder (yep, even the changelog.txt, doorstop_config.ini and winhttp.dll
2) Run the game (double-clicking h3vr.exe is fine) and quit to desktop.
3) Download the latest Deli, unzip it and copy-paste everything into the H3VR folder.
4) Run the game and quit to desktop.
5) Copy and paste betterhands file into the mods folder.

I hope this helps your problem.

**Comment by servermeta** [comment]
OH i did the download wrong then well thanks

**Comment by Nentox888** [comment]
I did all that but there still isn't a Deli folder

**Comment by Maiq-The-Dude** [comment]
@Nentox888, this mod no longer uses Deli so much of the above info isn't accurate anymore. I would recommend installing via [r2modman](https://thunderstore.io/package/ebkr/r2modman/) since that can automatically download & install mods along with their dependencies for you using Thunderstore. If you are still having problems, please open a new issue item. Thanks
