### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by ttd566** [Maiq-The-Dude/BetterHands#4]
On the newest version of the mod and game. Have all the necessary files and such. Tried downloading through Deli directly as well as through bonetomb. Can't manage to make it work. Latest BepInEx log included
[LogOutput.log](https://github.com/Maiq-The-Dude/BetterHands/files/6402432/LogOutput.log)

**Comment by Maiq-The-Dude** [comment]
Hi, do you have the game fully updated? The log file indicates you do not, so 1.1.1 will not work with your copy of the game. I would suggest updating and trying again. Otherwise, you should stay on 1.1.0.

![image](https://user-images.githubusercontent.com/18471731/116649454-e46ab200-a944-11eb-969b-8dc28ffadcdf.png)
